### PR TITLE
Image update, small wording change

### PR DESCRIPTION
**Pull request by matkuliak**
## Summary of the changes / Why this is an improvement

Sign-up UI update, wording improvement

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by matkuliak** [comment]
Is the statement about different sign-up options still true?

> If you intend to subscribe and deploy a cluster using a credit card - our recommended procedure - any of these signup methods will work. When coming from the Software as a Service (SaaS) marketplaces, however, restrictions apply. Only the Microsoft option allows you to deploy clusters on CrateDB Cloud when coming from the Microsoft Azure Marketplace. Similarly, for cluster deployment through our other cloud provider, AWS, you should use the Amazon Cognito signup service. The Cognito authentication service is indicated in the UI as Username & Password.

**Comment by SStorm** [comment]
> Is the statement about different sign-up options still true?

For now, but not much longer (Pending Marketplace re-integration story).

**Comment by SStorm** [comment]
I would also aim to simplify this paragraph as I had to read it several times to understand what it means :see_no_evil:

**Review by kojinkai — APPROVED** [review]

**Comment by matkuliak** [comment]
> I would also aim to simplify this paragraph as I had to read it several times to understand what it means 

Yeah, took me a minute to figure it out too, that's why I'm asking. Made a note of it, will do when Marketplace re-integration is done.

**Pull request merged**
